# Generated by Django 4.2.7 on 2023-11-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_tbltarjetas'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbltarjetas',
            name='numTarjeta',
            field=models.BigIntegerField(null=True),
        ),
    ]
