# Generated by Django 4.2.7 on 2023-11-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_tbltarjetas_numtarjeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbltarjetas',
            name='numTarjeta',
            field=models.IntegerField(null=True),
        ),
    ]
