# Generated by Django 4.2.7 on 2023-11-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_tbltarjetas_numtarjeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbltarjetas',
            name='tipoTarjeta',
            field=models.CharField(choices=[('Credito', 'Tarjeta de Crédito'), ('Debito', 'Tarjeta de Débito'), ('Prestamo', 'Préstamo'), ('Efectivo', 'Efectivo')], max_length=20),
        ),
    ]
