# Generated by Django 4.2.7 on 2023-12-04 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_tblingresos_tarjeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbltarjetas',
            name='cantidadDisponible',
            field=models.BigIntegerField(null=True),
        ),
    ]
